# Generated by Django 4.1.6 on 2023-02-25 06:45

from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_hotel_email_hotel_hotel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=hotel.models.designation_directory_path)),
                ('footer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=hotel.models.hotel_directory_path)),
                ('img_caption', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='hotel.hotel')),
            ],
        ),
    ]
