# Generated by Django 4.1.6 on 2023-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_designation_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
