# Generated by Django 4.1.6 on 2023-02-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_designation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_proof',
        ),
    ]
