# Generated by Django 4.1.6 on 2023-02-26 15:04

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_user_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hour_1_price',
            field=models.CharField(blank=True, default='149', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hour_2_price',
            field=models.CharField(blank=True, default='249', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hour_3_price',
            field=models.CharField(blank=True, default='349', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hour_4_price',
            field=models.CharField(blank=True, default='400', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel_image',
            name='image',
            field=models.ImageField(blank=True, upload_to=hotel.models.hotel_img_directory_path),
        ),
    ]
