# Generated by Django 4.1.6 on 2023-02-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_hour_1_price_hotel_hour_2_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='near_by',
        ),
        migrations.CreateModel(
            name='Near_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(blank=True, max_length=255)),
                ('reference_distance', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='near_by', to='hotel.hotel')),
            ],
        ),
    ]
