# Generated by Django 4.1.6 on 2023-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult_count',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_count',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
