# Generated by Django 4.1.6 on 2023-02-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_booking_adult_count_booking_child_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time_form',
            new_name='time_from',
        ),
    ]
